### PR TITLE
Move to recent log4j to remediate log4j vulnerability.

### PR DESCRIPTION
**Pull request by kaluzniacki**
I had to update log4j version to deal with the recent log4j vulnerability.
Hope this is helpful to you.

### CODE REVIEW

**Comment by mkowsiak** [comment]
Thanks. I appreciate it, however, please note that this repository doesn't maintain history and pull requests are not visible once new code is pushed into repo. In fact, there are more updates coming really soon: bumped up scala version, JVM version and JNA version.

Cheers and happy coding

**Comment by mkowsiak** [comment]
It will be much cleaner and easier to modify - I have added some changes that made this sample version proof.

**Comment by kaluzniacki** [comment]
Happy to contribute in any way - your examples saved me a boatload of time a few years back, and while I don't do much Java these days we do occasionally have to interface to some java library. Thanks for putting your work out here.

**Comment by Mervyen** [comment]
> It will be much cleaner and easier to modify - I have added some changes that made this sample version proof.

I am sorry to write this issue here, casuse I can't find other ways to contact you. if this bothers you, sorry again.

I have a question about https://www.youtube.com/watch?v=8Cjeq4l5COU , JNI code debug.
when I use clion, I got this error:
> error: attach failed: attach failed (Not allowed to attach to process. Look in the console messages (Console.app), near the debugserver entries, when the attach failed. The subsystem that denied the attach permission will likely have logged an informative message about why it was denied.)

and I came to the console.app got this error:
image
this question had confused me for weeks, have you ever encounter with this problems?

**Comment by mkowsiak** [comment]
It's doable :) But it's pain in the neck. What you have to do is:

- create a certificate to perform code sign: [https://www.owsiak.org/running-gdb-in-macos-sierra/](https://www.owsiak.org/running-gdb-in-macos-sierra/)

- get entitlements of your java code

```
codesign -d --entitlements :- /Library/Java/JavaVirtualMachines/jdk-11.0.13.jdk/Contents/Home/bin/java
```

- merge the entitlements with something like this (source: [https://crystalidea.com/blog/debug-your-apps-on-macos-with-qt-creator-lldb-workaround](https://crystalidea.com/blog/debug-your-apps-on-macos-with-qt-creator-lldb-workaround)):

```
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>com.apple.security.get-task-allow</key>
    <true/>
</dict>
</plist>
```

- code sign `java`

```
sudo codesign -f -s "jvm-debugger" --entitlements ./debuggee-entitlement.xml /Library/Java/JavaVirtualMachines/jdk-11.0.13.jdk/Contents/Home/bin/java
```

- you can now attach to your `java` process

```
lldb /Library/Java/JavaVirtualMachines/jdk-11.0.13.jdk/Contents/Home/bin/java
(lldb) target create "/Library/Java/JavaVirtualMachines/jdk-11.0.13.jdk/Contents/Home/bin/java"
Current executable set to '/Library/Java/JavaVirtualMachines/jdk-11.0.13.jdk/Contents/Home/bin/java' (x86_64).
(lldb) run
Process 1230 launched: '/Library/Java/JavaVirtualMachines/jdk-11.0.13.jdk/Contents/Home/bin/java' (x86_64)
Process 1230 stopped
* thread #3, stop reason = signal SIGSEGV
    frame #0: 0x000000010b60352d
->  0x10b60352d: movl   (%rsi), %eax
    0x10b60352f: leaq   0x30(%rbp), %rsi
    0x10b603533: movl   $0x10000, %eax            ; imm = 0x10000
    0x10b603538: andl   0x4(%rsi), %eax
Target 0: (java) stopped.
(lldb) quit
```

# Update

You can find detailed, step by step instruction here:  [LLDB and attach failed while debugging JNI code](https://www.owsiak.org/lldb-and-jni/)

**Comment by Mervyen** [comment]
Thank U so much!!! I had put issues on jetbrains, lldb project, apple. Finally, I get the answer.
Thanks again!!!

**Pull request closed without merging**
